[package]
name = "control_panel_gui"
version = "0.1.0"
edition = "2021"
default-run = "ctrl-panel"

[dependencies]
gtk = { version = "0.9.6", package = "gtk4" }
adw = { version = "0.7.2", package = "libadwaita", features = ["v1_4"] }
clap = {version = "4.5.37", features = ["derive", "env"]}
regex = "1"
zbus = "5.5"
futures = "0.3"
log = "0.4.27"
syslog = "7.0.0"

env_logger = "0.11.8"
tokio = {version = "1.44", features = ["rt", "time", "macros"]}
async-channel = "2.3.1"

serde_json = "1.0"
chrono = "0.4"
octocrab = "0.43"
serde = { version = "1.0", features = ["derive"] }
http = "1.0.0"
secrecy = { version = "0.10.3", features = ["serde"] }
toml = "0.8.20"

givc-client = { git = "https://github.com/tiiuae/ghaf-givc", branch = "main" }
givc-common = { git = "https://github.com/tiiuae/ghaf-givc", branch = "main" }
thiserror = "2.0.12"

[build-dependencies]
glib-build-tools = "0.20"

[[bin]]
name = "ctrl-panel"
path = "src/main.rs"
